language: java

sudo: false

# required for oraclejdk9
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9

#matrix:
#  allow_failures:
#    - jdk: oraclejdk9

before_install:
  - export MAVEN_SKIP_RC=true