language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9

before_install: export MAVEN_SKIP_RC=true

script: ./mvnw exec:java -Dexec.mainClass=com.example.Jdk9DemoWithMavenApplication

#matrix:
#  allow_failures:
#    - jdk: oraclejdk9
